canal_tp_nmp_acceptance_test:
    test_cases:
        journey:
            0:
                from: Brest
                to: Rennes
                expected: ~
            1:
                from: Brest
                to: Rennes
                expected: toolbox
            2:
                from: 23 Rue Paul Le Flem
                to: 44 place de la madeleine
                expected: walking_details
        schedule:
            0:
                stop_area: Brest
                expected: ~
            1:
                stop_area: Brest
                expected: toolbox
        multimodal:
            0:
                from: Brest
                to: Rennes
                expected: ~
            1:
                from: Brest
                to: Rennes
                expected: toolbox
        line_schedule:
            0:
                network: Auray Bus - Auray
                line: Ligne Jaune
                route: Ligne Jaune Brech-Centre Ville-Pluneret-P Océane
                expected: ~
            1:
                network: Auray Bus - Auray
                line: Ligne Jaune
                route: Ligne Jaune Brech-Centre Ville-Pluneret-P Océane
                expected: toolbox
        proximity:
            0:
                uri: Brest
                expected: ~