canal_tp_nmp_acceptance_test:
    test_cases:
        journey:
            0:
                from: Brest
                to: Rennes
            1:
                from: Rennes
                to: Brest
        stop_schedule:
            0:
                stop_area: Brest
            1:
                stop_area: Rennes
        multimodal:
            0:
                from: Brest
                to: Rennes
            1:
                from: Rennes
                to: Brest
        line_schedule:
            0:
                network: Auray Bus - Auray
                line: Bus Ligne Jaune
                route: Ligne Jaune Brech-Centre Ville-Pluneret-P Océane
            1:
                network: Auray Bus - Auray
                line: Bus Ligne Jaune
                route: Ligne Jaune P. Océane-Centre Ville-Pluneret-Brech
        proximity:
            0:
                uri: Brest
            1:
                from: Rennes