canal_tp_nmp_acceptance_test:
    test_cases:
        journey:
            0:
                from: Brest
                to: Rennes
                expected: ~
        schedule:
            0:
                stop_area: Brest
                expected: ~
        multimodal:
            0:
                from: Brest
                to: Rennes
                expected: ~
        line_schedule:
            0:
                network: Auray Bus - Auray
                line: Ligne Jaune
                route: Ligne Jaune Brech-Centre Ville-Pluneret-P Océane
                expected: ~
        proximity:
            0:
                uri: Brest
                expected: ~