canal_tp_nmp_acceptance_test:
    test_cases:
        journey:
            0:
                from: Caen
                to: Ouistreham
                expected: ~
        schedule:
            0:
                stop_area: Caen
                expected: ~
        multimodal: ~
        line_schedule:
            0:
                network: Bybus (Ville de Bayeux)
                line: 01 Reine Mathilde - Gare
                route: Reine Mathilde - Ste Patrice - Gare
                expected: ~
        proximity:
            0:
                uri: Caen
                expected: ~