canal_tp_acceptance_test:
    test_cases:
        journey:
            0:
                from: Orléans
                to: Gien
                expected: ~
            1:
                from: Orléans
                to: Gien
                expected: toolbox
            2:
                from: 1 boulevard Auger
                to: 20 avenue Carnot
                expected: walking_details
        schedule:
            0:
                stop_area: Gien
                expected: ~
            1:
                stop_area: Gien
                expected: toolbox
        multimodal: ~
        line_schedule:
            0:
                network: Ailebleue - CG36
                line: LRA FAVEROLLES > VALENCAY > CHATEAUROUX
                route: CHATEAUROUX > VALENCAY > FAVEROLLES
                expected: ~
            1:
                network: Ailebleue - CG36
                line: LRA FAVEROLLES > VALENCAY > CHATEAUROUX
                route: CHATEAUROUX > VALENCAY > FAVEROLLES
                expected: toolbox
        proximity:
            0:
                uri: Orléans
                expected: ~