canal_tp_nmp_acceptance_test:
    test_cases:
        journey:
            0:
                from: Rezé
                to: Commerce
                expected: ~
        schedule:
            0:
                stop_area: Rezé
                expected: ~
        multimodal: ~
        line_schedule:
            0:
                network: Ailebleue - CG36
                line: LRA FAVEROLLES > VALENCAY > CHATEAUROUX
                route: CHATEAUROUX > VALENCAY > FAVEROLLES
                expected: ~
        proximity:
            0:
                uri: Rezé
                expected: ~