canal_tp_nmp_acceptance_test:
    test_cases:
        journey:
            0:
                from: Nantes
                to: Cholet
                expected: ~
            1:
                from: Nantes
                to: Cholet
                expected: toolbox
            2:
                from: 140 Rue des Hauts Pavés
                to: 6 Chemin de la Houssinière
                expected: walking_details
# Waiting for SQWAL-2556
#            3:
#                from: Mangin (Nantes)
#                to: Commerce (Nantes)
#                expected: geovelo
        schedule:
            0:
                stop_area: Nantes
                expected: ~
            1:
                stop_area: Nantes
                expected: toolbox
        multimodal:
            0:
                from: Nantes
                to: Cholet
                expected: ~
# Waiting for PDLLD-1606
#            1:
#                from: Nantes
#                to: Cholet
#                expected: toolbox
        line_schedule:
            0:
                network: Irigo
                line: 05 Circulaire
                route: Circulaire sens A
                expected: ~
            1:
                network: Irigo
                line: 05 Circulaire
                route: Circulaire sens A
                expected: toolbox
        proximity:
            0:
                uri: Nantes
                expected: ~
