canal_tp_nmp_acceptance_test:
    test_cases:
        journey:
            0:
                from: Nantes
                to: Cholet
                expected: ~
        schedule:
            0:
                stop_area: Nantes
                expected: ~
        multimodal:
            0:
                from: Nantes
                to: Cholet
                expected: ~
        line_schedule:
            0:
                network: Irigo
                line: 05 Circulaire
                route: Circulaire sens A
                expected: ~
        proximity:
            0:
                uri: Nantes
                expected: ~