canal_tp_nmp_acceptance_test:
    test_cases:
        journey:
            0:
                from: Nantes
                to: Cholet
                expected: ~
            1:
                from: Cholet
                to: Nantes
                expected: tad
            2:
                from: Nantes
                to: Cholet
                expected: ~
        stop_schedule:
            0:
                stop_area: Nantes
            1:
                stop_area: Cholet
        multimodal:
            0:
                from: Nantes
                to: Cholet
            1:
                from: Cholet
                to: Nantes
        line_schedule:
            0:
                network: Irigo
                line: 05 Circulaire
                route: Circulaire sens A
            1:
                network: Irigo
                line: 05 Circulaire
                route: Circulaire sens B
        proximity:
            0:
                uri: Nantes
            1:
                from: Cholet