canal_tp_nmp_acceptance_test:
    test_cases:
        journey:
            0:
                from: Orléans
                to: Gien
                expected: ~
        schedule:
            0:
                stop_area: Orléans
                expected: ~
        multimodal: ~
        line_schedule:
            0:
                network: Agglobus - Bourges
                line: 1 FOULONNE - ROTTEE
                route: Foulonne - La Rottée
                expected: ~
        proximity:
            0:
                uri: Orléans
                expected: ~