canal_tp_nmp_acceptance_test:
    test_cases:
        journey:
            0:
                from: Orléans
                to: Gien
                expected: ~
            1:
                from: Orléans
                to: Gien
                expected: toolbox
            2:
                from: 102 rue Gutenberg
                to: 2 place de Domrémy
                expected: walking_details
        schedule:
            0:
                stop_area: Orléans
                expected: ~
            1:
                stop_area: Orléans
                expected: toolbox
        multimodal: ~
        line_schedule:
            0:
                network: Agglobus - Bourges
                line: 1 FOULONNE - ROTTEE
                route: Foulonne - La Rottée
                expected: ~
            1:
                network: Agglobus - Bourges
                line: 1 FOULONNE - ROTTEE
                route: Foulonne - La Rottée
                expected: toolbox
        proximity:
            0:
                uri: Orléans
                expected: ~