canal_tp_nmp_acceptance_test:
    test_cases:
        journey:
            0:
                from: Orléans
                to: Gien
            1:
                from: Gien
                to: Orléans
        stop_schedule:
            0:
                stop_area: Orléans
            1:
                stop_area: Gien
        multimodal:
            0:
                from: Orléans
                to: Gien
            1:
                from: Gien
                to: Orléans
        line_schedule:
            0:
                network: Agglobus - Bourges
                line: Bus 1 FOULONNE - ROTTEE
                route: Foulonne - La Rottée
            1:
                network: Agglobus - Bourges
                line: Bus 1 FOULONNE - ROTTEE
                route: La Rottée - La Foulonne
        proximity:
            0:
                uri: Orléans
            1:
                from: Gien