canal_tp_nmp_acceptance_test:
    test_cases:
        journey:
            0:
                from: Betton
                to: Bruz
                expected: ~
        schedule:
            0:
                stop_area: Betton
                expected: ~
        multimodal:
            0:
                from: Betton
                to: Bruz
                expected: ~
        line_schedule:
            0:
                network: Star - Rennes
                line: 151 Betton - Rennes (Hoche)
                route: Rennes (Hoche) - Betton
                expected: ~
        proximity:
            0:
                uri: Betton
                expected: ~