canal_tp_acceptance_test:
    test_cases:
        journey:
            0:
                from: Betton
                to: Bruz
                expected: ~
            1:
                from: Betton
                to: Bruz
                expected: toolbox
            2:
                from: 10 Rue Derval
                to: 78 Avenue de Cork
                expected: walking_details
        schedule:
            0:
                stop_area: Betton
                expected: ~
            1:
                stop_area: Betton
                expected: toolbox
        multimodal:
            0:
                from: Betton
                to: Bruz
                expected: ~
            1:
                from: Betton
                to: Bruz
                expected: toolbox
        line_schedule:
            0:
                network: Star - Rennes
                line: 151 Betton - Rennes (Hoche)
                route: Rennes (Hoche) - Betton
                expected: ~
            1:
                network: Star - Rennes
                line: 151 Betton - Rennes (Hoche)
                route: Rennes (Hoche) - Betton
                expected: toolbox
        proximity:
            0:
                uri: Betton
                expected: ~