canal_tp_nmp_acceptance_test:
    test_cases:
        journey:
            0:
                from: Reims
                to: Verdun
                expected: ~
            1:
                from: Reims
                to: Verdun
                expected: toolbox
            2:
                from: 85 avenue Cook
                to: 23 rue du Beauséjour
                expected: walking_details
        schedule:
            0:
                stop_area: Reims
                expected: ~
            1:
                stop_area: Reims
                expected: toolbox
        multimodal:
            0:
                from: Reims
                to: Verdun
                expected: ~
            1:
                from: Reims
                to: Verdun
                expected: toolbox
        line_schedule:
            0:
                network: Bus Etoile - Langres
                line: 1 Sabinus - Saints Geosmes - Citadelle - Bel Air - Gare SNCF
                route: Sabinus - Saints Geosmes
                expected: ~
            1:
                network: Bus Etoile - Langres
                line: 1 Sabinus - Saints Geosmes - Citadelle - Bel Air - Gare SNCF
                route: Sabinus - Saints Geosmes
                expected: toolbox
        proximity:
            0:
                uri: Reims
                expected: ~