canal_tp_nmp_acceptance_test:
    test_cases:
        journey:
            0:
                from: Reims
                to: Verdun
                expected: ~
        schedule:
            0:
                stop_area: Reims
                expected: ~
        multimodal:
            0:
                from: Reims
                to: Verdun
                expected: ~
        line_schedule:
            0:
                network: Bus Etoile - Langres
                line: 1 Sabinus - Saints Geosmes - Citadelle - Bel Air - Gare SNCF
                route: Sabinus - Saints Geosmes
                expected: ~
        proximity:
            0:
                uri: Reims
                expected: ~